apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "{{ .Values.deploymentLabel }}.{{ .Values.serviceName }}.hackathon.el8.io"
  gateways:
  - cory/my-gateway
  http:
  - route:
    - destination:
        host: {{ include "chart.fullname" . }}
        port:
          number: 80
